### ISSUE TITLE
Screen flickering when scrolled up specially on images.

### ISSUE THREAD

**Issue by alirizvi512** [petyosi/react-virtuoso#1034]
I have used this package in my project for showing feed on home page. In the home feed, there are text posts, video posts and also image posts. Now the problem is mostly image posts are flickering when scroll up. How can I fix this problem as its quite annoying the users and its experience. I need urgent help. Thanks.

Is there any possibility that we can increase the range of elemnets in the DOM. may be this would resolve the flickering stuff.

I am using nextjs 13.5.1 and our app is PWA.

**Comment by petyosi** [comment]
It's great that your company has chosen Virtuoso for your application. Since you expect urgent help, your company must sponsor the project - I'm happy to look into what can be improved afterward within your specific scenario. Use [the GitHub sponsorship option](https://github.com/sponsors/petyosi/sponsorships?sponsor=petyosi&tier_id=50934) to do so. 

Once I receive the sponsorship, you can contact me over email, I'm happy to help you further.
