### ISSUE TITLE
[BUG] huge delay  when providing restoreStateFrom

### ISSUE THREAD

**Issue by mbret** [petyosi/react-virtuoso#1116]
**Describe the bug**
When providing a `restoreStateFrom` to `Virtuoso` there is an important delay before the list is displayed. Does not matter the size of the list, I have the delay on lists with 10 items. The delay seems to be about 500ms.

Trying to thing about it a bit more, its the same issue with all the initial props. I believe it is because you introduce a volontary delay in order to hide the first calculation and by extension hide the first visual which would be wrong. However the delay seems extreme. A simple delay of a few ms or even immediate could maybe be enough?

`initialScrollTop` does not seem to introduce delay tho.

For now I am tracking the scroll position myself and restoring like this:

```typescript
  useEffect(() => {
    setTimeout(() => {
      if (restoreStateFromFirstValue.current?.type === "grid") {
        virtuosoGridRef.current?.scrollTo({
          behavior: "instant",
          left: 0,
          top: restoreStateFromFirstValue.current.state.scrollTop
        })
      }
      setIsReadyToBeShown(true)
    }, 10)
  }, [])


// jsx
<VirtuosoGrid
          ref={virtuosoGridRef}
          style={{
            ...style,
            visibility: isReadyToBeShown ? undefined : "hidden"
          }}
```

Less than 10ms and sometime the scroll does not restore (same problem with `restoreStateFrom` by the way, sometime it does not restore correctly and will just anchor to the top). Anyway, 10ms seems to be the sweet spot where the list is correctly calculated and where the call to scrolltop does work as expected.

**Reproduction**
[codesandbox](https://codesandbox.io/p/sandbox/nostalgic-fog-m9vc3q)

**To Reproduce**
Just toggle the button to hide / show both list. one with the state takes much longer to be rendered

**Expected behavior**
both should render around the same speed

**Comment by petyosi** [comment]
The delay is related to the initial topmost item calculation which `restoreStateFrom` uses under the hood. If you put `initialTopMostItemIndex={99}` at the second list you will see the delay there as well. The delay is anywhere between 50 and 150ms, from what I see in the performance timeline.

The underlying reason for the delays (which, as you've pointed out, [are internal](https://github.com/petyosi/react-virtuoso/blob/e27936a7b0f045326972d1128df5166653f5bca4/src/initialTopMostItemIndexSystem.ts#L55)) is that scrolling and (unfortunately) size measuring are asynchronous operations, which also have some variance in the browsers (I remember increasing a frame counter due to Firefox failing to restore state, for example). Timers are also quite unreliable, and are affected by, for example, more complex components being rendered.

I'm sure that there's a way to improve that by changing some of the data flow of the component. If you're interested, I'm happy to accept a PR. 

I'm going to close this issue not because it's fixed but because it's "make the whole thing better" kind of a thing.

**Comment by samavos** [comment]
@petyosi Do you have any plans to look into this further? Or, alternatively, any more light you could shed on the issue?

We've integrated react-virtuoso and the integration has gone really well and broadly the component always behaves very well for us.

Apart from this one scenario; setting the initial scroll position results in what is our view an unacceptable initial render delay. As it stands we're better off with a non-virtualised solution because even with fairly large lists of complex items the initial delay is shorter that way than waiting for this delay in the vast majority of cases.

I suppose what I was naively expecting was a `useLayoutEffect` doing the initial sizing, after which the correct scroll position could be computed and the component rendered, resulting in rendering immediately after computing this. But I can understand there is more to the problem than meets the eye, hence my question.

**Comment by petyosi** [comment]
@samavos I'm sorry that my work does not fit your acceptance criteria and that I don't meet your expectations. I hope you find a better solution for your needs.

**Comment by samavos** [comment]
@petyosi Just wanted to say thanks for the amazing library - in every other way it's better than other virtualisation libraries I've used. It's just this one scenario we've hit upon that doesn't fit our use-case so well. From what I understand of your answer, you're saying that this area isn't something you're actively looking at. If we can spare the time we may look into experimenting with the code in the library here and if we do make any progress we'll raise a PR. Thanks!

**Comment by vsMdulcio** [comment]
@samavos I was also getting a delay when rendering and this seemed to have stemmed from passing `initialItemCount` (not sure why exactly that, but in case this helps anyone else)
