### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mayurkalia99** [petyosi/react-virtuoso#1152]
Hey, my company took the subscription for the pro version for message-list. I am facing a weird flickering screen when images appear on messages. Giving an absolute dimension solves the issue but it is not looking good on some images.

I hope you help me with this as soon as possible because we need to go to mvp soon!

**Comment by petyosi** [comment]
Hi, 

The problem you describe is most likely due to a missing size for your image elements. You need to ensure that loaded content like images, videos, etc has their `width` and `height` dimensions set upfront so that when the browser loads it, the item does not get resized.
Assuming we're talking about user content, you should store the dimensions in your database when the users upload the image/video attachments. Usually, the CDN services have such a feature. Most chat interfaces are using a cropped, fixed size version of the assets for consistency. 

Should you need further help, you can contact me through the support@virtuoso.dev, mentioning your license key from the purchase.

Thanks,
