### ISSUE TITLE
Scrolling jumps when List rendered with largely varied height items 

### ISSUE THREAD

**Issue by Artoria-0x04** [petyosi/react-virtuoso#131]
I'm making a mobile chat interface, so list items are mixed with arbitrary long text and all sorts of images, and smooth scrolling is must need.

I discovered when list items height are largely varied, especially some item height larger than the viewport, scroll position will jump even you scroll slowly. Increasing `overscan` only helps a little and predefining the max item height is impossible. And I wonder if a huge overscan value will impact performance.
[https://stackblitz.com/edit/react-fwnr8h?file=ExampleComponents.js](https://stackblitz.com/edit/react-fwnr8h?file=ExampleComponents.js)

**Comment by petyosi** [comment]
Confirming that. It is a very hard problem to solve with the current approach, I even have a tag for it...

**Comment by Artoria-0x04** [comment]
Is there a quick fix now? Btw, what is bottom up scrolling?

**Comment by petyosi** [comment]
None that I can think of. Chat is bottom-up scrolling. I assume that the UI you are using is scrolled to the very bottom by default, and you scroll up.

**Comment by Artoria-0x04** [comment]
Yes, but this problem occurs on both ways, is there something special about bottom-up?

**Comment by petyosi** [comment]
Yes - there is. Prepending items causes a jump of the items below. Appending does not. Can you record a gif of what you mean?

**Comment by Artoria-0x04** [comment]
I'll try to append a gif later, I mean it will jump even when you scrolling down, both up and down. I presume the overscan is to deal with this, and I saw the discussion about one direction overscan, how about make overscan effective on both directions?

**Comment by jmeistrich** [comment]
I had found that setting defaultItemHeight to the minimum height of an item in my list appeared to fix the scroll jumping, but it also caused some scenarios where no items would render at all. Then I found that removing:
```
if (initialTopMostItemIndex) {
    initialOffsetList = initialOffsetList.setInitialIndex(initialTopMostItemIndex);
  }
```
from the top of offsetListEngine appears to fix it. It doesn't appear to cause any significant issues for me. But is there some problem this will cause that I'm not seeing?

**Comment by Artoria-0x04** [comment]
![Gif_20200611_201602](https://user-images.githubusercontent.com/1183568/84384389-79c36180-ac20-11ea-9b2a-9f08ec415446.gif)
Adding a gif on my phone

**Comment by Artoria-0x04** [comment]
@jmeistrich Adding `overscan` and `defaultItemHeight` seems works on single long height item, but not 2 long items together.

**Comment by jmeistrich** [comment]
Sorry @Artoria-0x04, I realized my comment didn't exactly apply (more relevant for https://github.com/petyosi/react-virtuoso/issues/89) so I moved it to that issue. But good to know that didn't fix this one.

**Comment by petyosi** [comment]
@Artoria-0x04 - thanks, I will investigate that. Definitely seems related to an item being longer than a viewport.

**Comment by petyosi** [comment]
@Artoria-0x04 the example you have provided indeed captures a bug, but a different one than I was thinking of. 

1) The long text generation was causing erratic re-renders, as each time the list item refreshed a different text was generated.

2) A jump happens, but not due to overscan or large items - but because the list is beyond the maximum DOM element height. A special logic is supposed to handle it, but it does not work as expected, [so I opened a new issue for it](https://github.com/petyosi/react-virtuoso/issues/134).

Find [a non-glitchy version of the example](https://stackblitz.com/edit/react-fwnr8h-ivgkmv?file=example.js) you provided. I am not sure if this will help you in your project, though. I assume that you can probably limit the count of items passed to the list.

Meanwhile, you can follow #134 for the development of the scrolling.

**Comment by Artoria-0x04** [comment]
I see. Randoms made the render process different on each cycle and unrepeatable. Sorry for the additional complexity. I'll look into the examples, thanks.
