### ISSUE TITLE
Dynamic item height

### ISSUE THREAD

**Issue by fabiospampinato** [petyosi/react-virtuoso#169]
Some times items are not all the same height, but the precise height for each of them is known beforehand, so I propose for the `itemHeight` prop to also accept the following signature:

```ts
( index: number ) => number | undefined
```

So that it can be called by the library when needed rather than taking expensive measurements and in general prodding the DOM.

**Comment by thecodrr** [comment]
Would love this as well.

@petyosi I tried implementing it but got stuck. Would love if you could give some pointers.

**Comment by petyosi** [comment]
I think that react-virtualized or react-window support that, no? What's missing there?

**Comment by fabiospampinato** [comment]
@petyosi well we want to use react-virtuoso instead, right? 😄

**Comment by petyosi** [comment]
@thecodrr @fabiospampinato I am missing something here - how do you know those heights? Would you be comfortable dumping them as some data structure (compressed array) in the component config, rather than having this function being called 100k times? 

Also, how does the list respond to viewport width changes? Or is this not an issue.

**Comment by thecodrr** [comment]
@petyosi the heights are known if, for example, you are rendering 2 or 3 different types of items in one list. If we know the height of all the different types of items, having a function to give the height to Virtuouso per item type would allow for different items to be rendered without issues.

For example:
Item A - 50px
Item B - 100px
Item C - 110px

As for calling the function 100k times, that is a genuine concern. The way `react-window` handles that is by caching the offsets.

We could, in practice, use a type to height map (object) but its much less flexible.

Right now, my use case for this feature is this:
I am rendering a group of note items and I want to render the group header but since VirtuousoList only allows me to give a single height, it isn't possible to do this. I know this can be handled by using GroupedVirtuouso but the data structure requirement for that is too much. I'd like to simply render the headers inline without any extra work (just a simple condition).

It must be noted that I made it to work, quite easily, with `react-window` but I am still interested in how it can be implemented in VirtuousoList.

**Comment by fabiospampinato** [comment]
> As for calling the function 100k times, that is a genuine concern.

There's no way calling a potentially trivial function to fetch the height 100k could be slower than prodding the DOM 100k times if not more.

**Comment by petyosi** [comment]
Giving this some thought - the component has to figure out the total height from the very start - so it needs to know all item heights upfront. That's why I am leaning towards a data structure rather than a function. FWIW, this could be done relatively easy - the `itemHeights` should be loaded in [this stream](https://github.com/petyosi/react-virtuoso/blob/master/src/engines/offsetListEngine.ts#L32). From there on, the logic of the `fixedItemHeight` can be applied, disabling the querying of the DOM.

**Comment by fabiospampinato** [comment]
@petyosi I don't think the height must be available for all items since the start, can't the library fall back to prodding the DOM if the height for some particular items can't be computed?

Regarding the shape of the API I think having a function would be much cleaner, often times I would imagine it would be in the form of: `item.type === 'foo' ? 20 : 30` or something trivial like that. 

If for whatever reason this function must be called at startup on all items of the list then the library can do it, building its own structure rather than offloading that to the user.

**Comment by petyosi** [comment]
@fabiospampinato I believe I understand what you suggest, however, I don't see how it can fit in the current rendering model. If you would like, we can have a quick call for brainstorming; ping me on the mail on my profile.

**Comment by dilizarov** [comment]
@petyosi another thing to consider is by having this, we wouldn't need to import both `react-window` and `react-virtuouso` into a product, but could instead choose to use one (this one!).

I got here because I noticed `Virtuoso` takes a fixedItemHeight prop and also an itemHeight prop... and I'm not sure what the point of the second one is if I have the first.

Cheers.

**Comment by petyosi** [comment]
@dilizarov `fixedItemHeight` is the v1 prop, `itemHeight` is deprecated. If you can post me a sandbox with what you are doing with react-window (and, if necessary, explain why virtuoso does not fit the case), that would help me a lot. 

My current understanding is that such callback would replace the `offsetHeight` prop access in `getChangedChildSizes` (see [implementation](https://github.com/petyosi/react-virtuoso/blob/a322420189e3394683af2cffd58e04823405aa15/src/hooks/useChangedChildSizes.ts#L4)). While doable, I highly doubt that it will result in any reasonable performance improvement. 

Please let me know if this makes sense.

**Comment by gajus** [comment]
I am rendering a large list of JSON documents, but rendering these documents using a lot of markup to provide syntax highlighting, e.g.

<img width="973" alt="Screen Shot 2021-05-05 at 11 15 11 PM" src="https://user-images.githubusercontent.com/973543/117241040-d068f980-adf7-11eb-9d03-b4c2063d475f.png">

It would be trivial for me to approximate height of each element at different container widths, or at least a lot faster than what `useChangedChildSizes` does.

**Comment by petyosi** [comment]
While not excluding the possibility of such API being a viable solution, I have seen it fail for the regular developer on multiple occasions - look no further react-window's GH issues for proof on the matter. 

With this being said, I am closing the issue as I have no intention to implement it. If someone is willing to contribute, feel free to reach out to me for guidance in the codebase.

**Comment by J6K** [comment]
@petyosi I have a similar issue with complex message types (images, polls, etc) causing a shift in the UI as they're loaded. If my prepended messages are all images, it pushes my top message out of view as the images are loaded. 

Open to making a PR if something needs to change on this end, would like some pointers/guidance 🙏🏼

**Comment by petyosi** [comment]
@J6K the behavior in this PR won't help you with what you describe. If you know the size of the images, set it as an attribute.

**Comment by J6K** [comment]
@petyosi thank you for the prompt response 🙏

So if my collection of messages are all varied in height, I can pass them along to virtuoso using itemSize? Or is it a different attr?

**Comment by petyosi** [comment]
No, fix the size of the image elements by setting their height attribute.
