### ISSUE TITLE
dataKey in version 1

### ISSUE THREAD

**Issue by exentrich** [petyosi/react-virtuoso#236]
Thank you so much for improving this library!
Right now I'm migrating to v1 and really miss `dataKey` attribute. Do v1 have another option to force re-render the list?

**Comment by petyosi** [comment]
@exentrich - I can restore it, but my hope is that the new `data` property can eliminate that workaround approach. Does it work for you?

**Comment by exentrich** [comment]
Unfortunately no. I have additional specific state like: active item index, does bulk mode is enabled and some other.
This attribute have been very useful. Would be great to have it again :) Please!

**Comment by petyosi** [comment]
Makes sense. I will look into it for 1.0.1, hopefully over the upcoming weekend.

**Comment by Ethorsen** [comment]
I'm also facing an issue on a single list that might be solvable with dataKey.

We allow the user in this list to click on items to select them.

There is this weird behavior where the data of the list wont change directly. But the rendered item might, based on a different data (the one that mutated after the click...)

My guess is that we could force Virtuoso to re-render items by changing the dataKey there.

**Comment by petyosi** [comment]
@Ethorsen @exentrich - I got to this today, but I am struggling with the right test case. Following what you mentioned, using the selection as an example, I [constructed this codesandbox](https://codesandbox.io/s/nifty-shape-qb99h?file=/src/App.tsx:293-371).

As you can see, wrapping `itemContent` in `useCallback` with the correct dependencies re-renders the component correctly. 

Can you please fork the sandbox above so that I can justify restoring the property? Thank you!

**Comment by Ethorsen** [comment]
Thx @petyosi.  After migrating almost all our lists, I can say that on our side we won't need this prop.

I would have used it on a single list because of the real bad way our data structure was handled in that particular component (can't control it all...)

**Comment by petyosi** [comment]
@exentrich feel free to reopen this if you get to a demo. Thanks.
