### ISSUE TITLE
GroupedVirtuoso List component is applied to sticky group 

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#237]
Hi,

When setting a List component.   It also seem to be applied to the current sticky group.

Quick sandbox to demonstrate the issue
https://codesandbox.io/s/recursing-bush-0m6uc?file=/src/App.js

![image](https://user-images.githubusercontent.com/1493968/102358177-3524d400-3f7d-11eb-9880-e9cc1aa04397.png)

You can see the styles being applied on the list correctly, but also on the sticky group.

Thx

**Comment by petyosi** [comment]
Correct. The custom list is used for the two lists: the scrollable and the sticky one. Is this an issue? If so, this could be fixed with a prop passed to the component very easy - a PR would help me.

https://github.com/petyosi/react-virtuoso/blob/master/src/List.tsx#L193 - the `showTopList` variable is true/false and denotes if the Items are rendered for the sticky or the main list.

**Comment by Ethorsen** [comment]
Its not an issue for us right now.  This is only something I noticed while experimenting with the library.    

I just though this was a bug as I don't see the sticky group item as a second/different list but simply as an individual item.

I guess for future usage, if that props is being passed down to the list component it could help to apply different logics.  Something like isTopList or isStickyList.

But like I said,  this is not an issue right now.
