### ISSUE TITLE
"localRef.addEventListener is not a function", when using custom scroller

### ISSUE THREAD

**Issue by adsee42** [petyosi/react-virtuoso#240]
Thanks for this great package!

I'm using `OverlayScrollbars` through all my react app to render custom scroll bar.
I would love to have unified scroll bar style for lists rendered with `react-virtuoso`, but custom `Scroller` component gives a type error: "localRef.addEventListener is not a function".

see [this](https://codesandbox.io/s/customize-scroller-bug-forked-dzixf?file=/src/App.js)

Any idea?

**Comment by petyosi** [comment]
@adsee42 the `ref` needs to be assigned to a **DOM element** so that Virtuoso can bind to its scroll events and command it with `scrollTo` and `scrollBy`. I may suggest that you look into the overlayscrollbars implementation for a way to do that. Feel free to post updates in this issue when you progress. Thanks!
