### ISSUE TITLE
itemContent called for empty groups

### ISSUE THREAD

**Issue by mthenw** [petyosi/react-virtuoso#263]
Hi, 

first of all thanks for the great project! 

I have one question.

```
() => {
  const groupCounts = useMemo(() => { 
    return Array(10).fill(0)
  }, [])


  return (
    <GroupedVirtuoso
      groupCounts={groupCounts}
      groupContent={index => {
        return (
            <div style={{ backgroundColor: 'var(--ifm-background-color)' }}>Group {index * 10} &ndash; {index * 10 + 10}</div>
        )
      }}
      itemContent={(index, groupIndex) => {
      console.log("itemContent", index, groupIndex)
        return (
              <div>{index} (group {groupIndex})</div>
        )
      }}
    />
  )
}
```

Why `itemContent` is called? The console.log output is `itemContent 0 9`, meaning it's called only once, for the last group. What's the purpose of that?

**Comment by petyosi** [comment]
Hey, let's start off with the fact that I did not consider empty groups to be a valid scenario. From what I see, they kind of seem to work, though. Not sure if you won't face incorrect `groupIndex` argument values at some point. 

Up to your question: `itemContent` is called for the initial item size estimations. The component does a "probing" render cycle using one group and one item, using the first group and the first item, but since the group is zero-sized, the `groupIndex` gets transposed to the last group index. Again, not something which I accounted for. 

I am not sure how much of an issue this is on your side. For what is worth, I would probably consider a list full of empty groups as an empty one and not display anything.  

It would be great if you can give some context on the UI you are building, perhaps I can help further.

**Comment by jonathaneckman** [comment]
@petyosi first, thank you for this component. Its saving me a ton of time. A use case I'm facing a use case for empty groups: an agenda view calendar with events. I want to show every calendar day (group) but not every calendar day has an event (item). Example:

- 1/1
   - Event at 9 AM
   - Event at 2PM
- 1/2   <!-- empty group
- 1/3
   - Event at 11AM

Would you consider making this supported in the future or do you have a recommendation for a better way to go about it?

**Comment by petyosi** [comment]
@jonathaneckman thanks for sharing the use case - indeed, this is a valid one. I would like to implement proper support for empty groups, but I am not sure when I will be able to get to it, priority wise.
