### ISSUE TITLE
Initial render delay

### ISSUE THREAD

**Issue by fabiospampinato** [petyosi/react-virtuoso#264]
I just finished upgrading to v1, and I've noticed a new issue, below there's a screen recording of the app I'm working on, where I'm basically unmounting and than re-mounting the first two columns of the app.

As you can see there's a bit of a delay between when the columns themselves show up and when their content shows up. This makes the app feel slower, I think it would be better to address this performance issue when rendering a list for the first time.

Just reverting the commit where I upgraded to v1 fixes this, so I guess something in v1 is causing this.

https://user-images.githubusercontent.com/1812093/104776912-bd5fea00-5772-11eb-868f-3930312fa323.mov

**Comment by petyosi** [comment]
That's interesting. My bet is that the specific config causes more rendering cycles compared to v0.x. I found and addressed several issues like this since the initial v1 release. 

Goes without saying, a reproduction of the issue is going to help me determine the issue.  Alternatively, I might be able to spot something based on the Virtuoso props which you use.

**Comment by petyosi** [comment]
v1.4.0 comes with a new way of propagating properties to the component internals. This reduces the initial render count, but I have no way to tell if this will affect your setup. Please re-open this if you build a repro. Thanks!
