### ISSUE TITLE
Refuses to render items at certain zoom levels

### ISSUE THREAD

**Issue by andrewfluck** [petyosi/react-virtuoso#268]
At some zoom levels, when a list is empty or almost empty, the items refuse to display. If a list is empty and a message gets sent, the item gets populated as the list gets recomputed.

I can't really send a reproducible demo with code, however, I can set up a demo of the app in question, it's easier to demo it to you manually as if I post a chat link, people may spam it and ruin the demonstration of the issue.

If you would like to see and spot any issues with the implementation of your library and correct something, that's always welcome too, but there's no pressure to do so. We've been scratching our heads at this for a while and it's impacting our product.

**Comment by petyosi** [comment]
This could be due to floating numbers being reported from the DOM - I can't really say unless I have a reproduction. I have also seen a problem where the DOM items are not painted, despite being correctly rendered and placed - but this was resolved at some point. 

I browsed the example site at 67% zoom level on Mac Chrome - the examples worked fine. I also zoomed out on [this example](https://h7s27.csb.app/), and it seems to work as expected. 

Leaving the zoom issue aside, I am happy that you considered the library for your product. You may consider one of the sponsorship options in Github or Patreon - it will let me spend more time on it, helping its development and maintenance.
