### ISSUE TITLE
[BUG] Stick to bottom not working when loading images 

### ISSUE THREAD

**Issue by focux** [petyosi/react-virtuoso#293]
**Describe the bug**
As the title says, stick to bottom doesn't work when loading async elements like images. I think that the list should scroll or keep sticked to the bottom after the image or any other async element has been loaded. 

If it helps, I'm using version 1.5.6.

**Reproduction**
https://codesandbox.io/s/pensive-moser-8bn2y?file=/src/App.js

**To Reproduce**
Load the sandbox and wait for the images to load

**Expected behavior**
Keep the scroll sticked to the bottom after the images have loaded.

**Comment by petyosi** [comment]
`followOutput` monitors and acts only the initial item sizing. Pulling the list to the bottom each time the contents of the items get resized would be too much magic and might not be what the users expect.

From what I've seen in the chat/feed UI, media content is injected with fixed size so that the additional UI readjustments are avoided - that's what I would recommend for best UX. If this, however, is not feasible for your case, you can scroll down the list when the images get loaded - [here's an example on how to do it using `scrollToIndex`](https://codesandbox.io/s/musing-poitras-vjio3).

**Comment by focux** [comment]
Fair enough, that works for me. Thank you.
