### ISSUE TITLE
scrollToIndex at component mount

### ISSUE THREAD

**Issue by doubld** [petyosi/react-virtuoso#323]
Hi, I tried to scroll the list by "scrollToIndex" function, after the component is mounted:

useEffect(() => {
      virtuoso.current.scrollToIndex({
        index: 25,
        align: "center",
        behavior: "smooth"
      })
}, []);

but it doesn't seem to work. Can you help me? Thanks.

**Comment by petyosi** [comment]
TL;DR: Don't do that. Use `initialTopMostItemIndex` prop instead, it will skip the rendering of the initial items (index 0-20). This is very important for large lists, as you won't have to load data for the top of the list.

However, if you still want to do it for some reason, wrap the call in a timeout of some sort so that the component is ready.

**Comment by petyosi** [comment]
Yes, in that case, the easiest way to achieve it is through timeout.
