### ISSUE TITLE
[BUG] endReached does not work together with initialItemCount

### ISSUE THREAD

**Issue by horprogs** [petyosi/react-virtuoso#341]
**Describe the bug**
We have:
Virtuoso with defined `initialItemCount` and `endReached`. Also we have conditional rendering to show loading block or virtuoso table
```
<div>
  {data.length ? (
    <Table data={data} loadMore={loadMore} />
  ) : (
    <div>Loading...</div>
  )}
</div>
```

And under these 3 circumstances `endReached` does not work. If we remove conditional rendering it will work, or if we remove `initialItemCount` it will work too.

**Context:**
I have SPA and I use jest for testing. To be able to test properly I have to specify `initialItemCount`. I decided just to put `initialItemCount={data.length}` and I thought it should work both for browser and jest environment. But caught this bug.

**Reproduction**
https://codesandbox.io/s/small-worker-g3znf

**To Reproduce**
1. Scroll to the bottom
2. Console log does not print REACHED
3. More items are not fetched

**Expected behavior**
1. Scroll to the bottom
2. Console log prints REACHED
3. More items are fetched

**Comment by petyosi** [comment]
Hey, I checked what's going on. 

- `endReached` is triggered when the last item of the list is rendered for the first time. 
- component mutes events emitting during the component mount setup.

In your setup, `endReached` gets triggered because the entire list (including the last item) gets rendered initially. This happens during the initial setup, so the event isn't emitted (hence no `console.log`). I can make the event emitting work, but you will end up with an immediate additional `loadMore` call when the first one is done. I am fairly certain that you don't want that behavior.

If you need a simple workaround to make that work, you can use `data.length - 1` as the `initialItemCount` prop value. From a performance standpoint, however, I would not display the entire data initially.

**Comment by horprogs** [comment]
Thank you for this explanation! I think `data.length - 1` works in my case, I'll close this issue
