### ISSUE TITLE
[BUG] GroupedVirtuoso seems to miscalculate heights based on number of groups

### ISSUE THREAD

**Issue by omgoshjosh** [petyosi/react-virtuoso#346]
First off, this repo and project is TIGHT. i want to give and say thanks. my company may one day sponsor this project and/or i may be interested in contributing some time. i really like the bits of source i've seen while investigating this bug.

**Describe the bug**
GroupedVirtuoso seems to miss the final items in the data array (100k items) and it seems to correspond the the number of groups (size of groupCounts array). maybe some height/scroll miscalculation not accounting for groups? maybe it's operator error and i just need to use different css classes/styles or something.

**Reproduction**
https://codesandbox.io/s/groupedvirtuoso-rangechanged-qgg75?file=/src/App.tsx

**To Reproduce**
1. Scroll all the way to the bottom (grab the scroller to get there faster, 100k is a lot!)
2. observe the rendered range when looking at the last rows is missing about as many items as there is groups (4 in the top example and 10 in the bottom example)

**Expected behavior**
I guess i would expect the rows to be consistent with the data? that is there should be 100k rows and the last items should appear up to 99999

**Screenshots**
![image](https://user-images.githubusercontent.com/1960929/115601389-9eea1d00-a292-11eb-9772-86cc885be443.png)

**Desktop (please complete the following information):**
 - OS: MacOS (macbook pro)
 - Browser: Brave (chrome based)

**Additional context**
PROBABLY a different bug, but putting a footer in combination with this bug causes a "maximum depth exceeded" error because the rangeChanged callback is called repeatedly.

In the provided codesandbox, i've added some commented out props (components/footer/rangeChanged) you can swap in with a 1 second debounce on `rangeChanged` so it doesn't lock up your browser tab. i think these two issues are related but that there's a single underlying cause based on calculating "listBoundary" i saw in the source code .

**Comment by petyosi** [comment]
@omgoshjosh the problem is a trivial one; a missing feature. GroupedVirtuoso does not correctly support `data` prop; rather, it "inherits" it from the flat list, causing the mischief you observe. Removing the `data` prop makes the example run for me, including the uncommenting of the footer (as far as I saw). 

There's no real reason to not support `data` in grouped virtuoso apart from my limited resources. Notice that the correct implementation should eliminate the necessity of setting `groupCounts`, as they should be inferred from the data.

**Comment by omgoshjosh** [comment]
Excellent thanks.
