### ISSUE TITLE
[BUG] - Footer height issue

### ISSUE THREAD

**Issue by isBatak** [petyosi/react-virtuoso#364]
When the footer height is bigger the viewport strange things are happening. 
It will load next page but not more than that. I will be stuck to the loading element.
This is an issue if we have a skeleton loader in the footer which have the same number of elements as the page and it exceeds the size of the viewport.

**Reproduction**
https://codesandbox.io/s/virtuoso-footer-height-issue-9756k?file=/src/App.js

**To Reproduce**
1. Scroll to the bottom
2. check the console

**Expected behavior**
To continue loading the next pages.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur.
 - Browser Chrome 90.0.4430.212

**Comment by petyosi** [comment]
@isBatak True, kind of erratic on my side, but definitely reproducible. Will take a look.

**Comment by petyosi** [comment]
Upon further investigation, this seems to be caused by a (rather interesting) browser behavior. If the footer is tall enough to occupy the entire visible area, appending items above it causes the browser to auto-reposition so that the same element is kept into the viewport, resulting in the behavior you observe. In fact, it is not stuck - if you scroll up, the `endReached` will be triggered. Nevertheless, it's not a logical behavior. Interestingly enough, macOS Safari does not do it. 

I don't see a way to fix that in a reliable way, while not potentially breaking other paths. Reducing the footer height by just 1px resolves the problem.
