### ISSUE TITLE
[BUG] Endless scrolling bug when using Chakra UI components

### ISSUE THREAD

**Issue by isBatak** [petyosi/react-virtuoso#366]
**Describe the bug**
This is a continuation of #364. 
I investigated it more and figure out that my problem is not just footer height, it seems like strange scroll behavior is connected to Chakra UI lib, somehow...
In the code sandbox example, provided below, we can see that `endReached` gets triggered multiple times regardless of the footer size (which is 100px now).

**Reproduction**
https://codesandbox.io/s/virtuoso-chakra-ui-issue-q5s28?file=/src/App.js

**To Reproduce**
1. Open sandbox
2. Strange behavior appears on the first load or on the first scroll

**Expected behavior**
`endReached` should be triggered only once when the user scrolls to the bottom.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur.
 - Browser Chrome 90.0.4430.212

**Additional context**
Example uses [Chakra UI](https://chakra-ui.com/) which uses [Emotion.js](emotion.sh), an CSS-IN-JS library that interpolates CSS in runtime and maybe triggers auto-reposition 🤷‍♂️

@petyosi I'm willing to contribute if you can point me where to start :D

**Comment by petyosi** [comment]
If I see correctly, the problem is that the rendering is "unstable" - each re-render will display different random text - that's not supported. Exactly the same problem has been discussed in at least one closed issue here - please browse the closed issues section.

I may suggest that you spend some time simplifying your examples and removing the various "moving parts" - random text, styling, etc, so that you can understand better what's wrong. There are plenty of working examples on the site which you can use as a starting point and gradually work up to your requirements.
