### ISSUE TITLE
[BUG] Unexpected scroll behaviour with overscan in case of prepending items

### ISSUE THREAD

**Issue by harshitdavda** [petyosi/react-virtuoso#370]
**Describe the bug**
Unexpected scroll behaviour with overscan in case of prepending items

**Reproduction**
https://codesandbox.io/s/prepending-items-with-custom-height-with-overscan-40cmz

**To Reproduce**
1. Scroll to top of the list
2. When items are prepended, scroll position is not maintained

**Expected behavior**
Scroll position should be maintained when prepending items

**Comment by petyosi** [comment]
I'll take a look, but it might be hard to fix. Notice that I would not recommend overscan and regret introducing it. It does not solve any actual performance problems, but rather creates more.

**Comment by petyosi** [comment]
Took a look. It is hard to fix, the only viable way would introduce blinking. 

Long story: pretending items preemptively scrolls down using the default height of the items to be prepended, so that they never get rendered. Overscan breaks that assumption since it renders the prepended items. If some of them happen to have different heights, the preemptive scrolling is no longer at the valid position. 

Surely, the list can measure the newly introduced items and re-fix the position - but that would cause the blink I referred to. In fact, some time ago, the implementation looked like this and it caused a poor experience. 

This brings me back to the original recommendation - don't use overscan. Fewer items in the dom yield better performance.
