### ISSUE TITLE
[BUG] startReached and endReached called in succession

### ISSUE THREAD

**Issue by Venugopal46** [petyosi/react-virtuoso#383]
**Describe the bug**
In a particular scenario,`startReached` and `endReached` called in succession.

**Reproduction**
https://codesandbox.io/s/romantic-mountain-tzfbw

**To Reproduce**
1. once initial items are loaded, scroll up to fetch previous items
2. observe the console logs

**Expected behavior**
only `startReached` should be called.

**Additional context**
This issue isn't happening if I fetch the next items first and then scroll up to fetch previous items.

**Comment by petyosi** [comment]
I can't observe something that does not work right, can you send a screen record?

**Comment by Venugopal46** [comment]
https://user-images.githubusercontent.com/7404447/121542646-f18bbe00-ca25-11eb-811f-9659934fd625.mov

let me know if this helps. Thanks.

**Comment by petyosi** [comment]
That does not look right, but I can't reproduce. Here's how it works on my side:

https://user-images.githubusercontent.com/13347/121636861-34cf4680-ca91-11eb-9c2b-1685f69c6bb0.mov

**Comment by Venugopal46** [comment]
I mentioned that this issue is happening only in one scenario. scroll up after initial load. I also mentioned that this issues isn't happening if you scroll down first to fetch next page.

**Comment by petyosi** [comment]
Nah, got it. I was not reading you report correctly

**Comment by petyosi** [comment]
I examined the linked example in further detail, and this is going to be quite hard to fix on the lib side. Let me explain:

When scrolling up and new items are prepended, the lib scrolls **down** first in order to compensate for the newly introduced content. When items are prepended, the browser shifts back to where the list should be.

In your case, however, the initial amount of items is small, and the scroll-down action reaches the bottom of the list. It is fairly easy to avoid that - you need to bump the amount of the initially loaded items. 

On a side note, you are also using negative values for the `firstItemIndex` - which causes some internal calculation issues. Start from a really large item instead. 

I will keep this bug open for now, but again, fixing it is going to be quite hard (I need to detect that scrolling and ignore the end reached).
