### ISSUE TITLE
[BUG?] Wrong "initial" range

### ISSUE THREAD

**Issue by Donorlin** [petyosi/react-virtuoso#396]
**Describe the bug**
Hi there, big fan of your package. I have noticed in your example [https://virtuoso.dev/range-change-callback/](https://virtuoso.dev/range-change-callback/) that when I load a page "current visible range" is 0-4 but when I scroll a bit down and back up (force rangeChanged being called), the range is suddenly 0-5...

We are having this problem in our application too, so I am kind of glad I have found it in your example.. because it would be impossible for me to show you our use-case ... for many (not important) reasons...

**To Reproduce**
1. Go to https://virtuoso.dev/range-change-callback/
2. Range is 0-4
3. Scroll a bit down and back to top (so rangeChanged is called)
4. Range is 0-5 even though you see the same items as at the start

Thank you for your answers !

**Comment by petyosi** [comment]
That's a bug that's indeed, thank you! Will look into it

**Comment by Donorlin** [comment]
Thank you for your quick response! We are still using 0.* version of react-virtouso. Is there any chance your future fix can be released in the old version as well? Sadly we have no space right now to fluently upgrade to 1.* version (tried).. and we really need fix for this in production.

**Comment by petyosi** [comment]
Ah, no - sorry; I have completely erased the implementation of 0.x from my head. 

But you should move away from 0.x. Compared to it, 1.x is much more optimized. There's a migration guide available [for the purpose](https://virtuoso.dev/migrate-v0-to-v1/).

**Comment by petyosi** [comment]
@Donorlin I examined the case you describe. The behavior is indeed inconsistent, but I won't be able to address it - here's why. 

Let's use a simple case of `300px` tall list with `30px` tall items. When the list is rendered initially, it calculates that it will take exactly 10 items (range 0-9) to fill the viewport. Scrolling 5px down, it will need *11* (0-10), since the first one is partially hidden. 

The key moment here is that the list re-calculates the items when the currently rendered ones are insufficient to fill in the current location of the viewport - [here's how the code looks](https://github.com/petyosi/react-virtuoso/blob/3bfea2846ea6427afbe07713aa282e266abe2de4/src/sizeRangeSystem.ts#L49-L55).

Pseudo-code below:
```tsx
if (listTop > scrollTop) {
  // re-render, add items to the top, maybe remove items from the bottom.             
}

if (listBottom < scrollTop + viewportHeight) {
  // re-render, add items to the bottom, maybe remove items from the top
}
``` 

The range logic, however, **does not actively seek items no longer visible in the viewport which are suitable for removal**. Going back to our example, if we scroll 5px up (back to the top of the list), the items don't get recalculated because the list fully covers the viewport, and the item at index `10` will remain in the DOM. It is not necessary, but there's no recalculation cycle to clean it up. 

I would rather not touch that part of the code - altering that logic can easily lead to increased re-rendering and potential UI lockups. Based on several other issues, I can point you towards [this sample implementation](https://github.com/petyosi/react-virtuoso/issues/118#issuecomment-642156138) (which, by the way, targets 0.x but will work with 1.x) that uses intersection observing as a way to detect the visibility of an item.
