### ISSUE TITLE
[BUG] overscan leads to skipped indices in rangeChanged 

### ISSUE THREAD

**Issue by eliasws** [petyosi/react-virtuoso#411]
**Describe the bug**
If overscan is enabled, the reported indices reported by rangeChanged are not precise. Several indices get skipped while scrolling.

**Reproduction**
https://codesandbox.io/s/react-virtuoso-scrolling-issue-forked-h6ok4?file=/src/App.js:288-300

**To Reproduce**
1. Scroll
2. Check console output of rangeChanged
3. The reported indices are wrong e.g. 

{startIndex: 24, endIndex: 37}
{startIndex: 28, endIndex: 41}
{startIndex: 32, endIndex: 45}
{startIndex: 35, endIndex: 48}

In this example instead of steps of 1 the steps are 3-4.

**Expected behaviour**
The start- and the end-index should be reported in steps of 1.

**Screenshots**
-

**Desktop (please complete the following information):**
 - MacOs, Android
 - chrome, chrome Mobile

**Additional context**
Same behaviour for the scrollSeekConfiguration.change callback.

**Comment by petyosi** [comment]
What you describe is exactly how overscan should work. The point of the property is to reduce the re-renders by grabbing larger chunks of items. The behavior of the property (somewhat confusing) is different from react-window. 

On a side note, I don't recommend using overscan in general, and I regret introducing it. It does not solve any problems, people just waste their time by trying to workaround a slow rendering with it.

**Comment by eliasws** [comment]
@petyosi Thanks for the clarification and the great library. In my understanding the "overscan" property would just work as "extended viewport", increasing the number of rendered items like shown in the image below. But if i understand it correctly it "waits" until the overscan defined is filled with new messages and rerenders the view + the overscan all at once?

![overscan](https://user-images.githubusercontent.com/19492473/126307476-5a160819-3473-44cc-913b-706758fdb468.png)

**Comment by petyosi** [comment]
You got it right. Your initial understanding (static extension of the viewport) is probably the more intuitive one, as many people are assuming that is how it will work. But it does not. Instead, an overscan is applied when loading new messages in a certain direction. Rather than loading messages one by one, it will cause messages enough to fill in the `overscan` amount of pixels to be added. It felt like a good idea back in the day. 

However, as I said, I am not proud of that design decision. Maybe at some point, I have to just release `v2.0` and change that behavior.
