### ISSUE TITLE
[BUG] GroupedVirtuoso, itemCount (index, groupIndex); index is not reset inbetween group index changes

### ISSUE THREAD

**Issue by wibed** [petyosi/react-virtuoso#427]
**Describe the bug**
the index keeps incrementing even after the group index has changed.

**Reproduction**
https://codesandbox.io/s/unruffled-davinci-rs2be?file=/src/App.js

**To Reproduce**
see reproduction.

**Expected behavior**
the index to reset to 0 after the groupindex has updated

**Comment by wibed** [comment]
maybe i am missing something and this is on purpose. 
i cant find any explanation for this particular design and opened a bug report

**Comment by petyosi** [comment]
That's by design. The virtualized list assumes you will fetch data from remote locations, it works best if you use a single array of items that are sorted by the group they are in (Think in SQL - offset, limit, etc). It does deserve a better explanation, but you can take a look at what I had in mind here: https://virtuoso.dev/grouped-with-load-on-demand/
