### ISSUE TITLE
[BUG] - Scroll position jump around when items doesn't have a fixed sizes and are loaded lazily.

### ISSUE THREAD

**Issue by frnk94** [petyosi/react-virtuoso#428]
**Describe the bug**
When used with elements that are loaded lazily the scrollbar jump to random places or act erratically. We used virtuoso to handle our live feeds and we need to put some Ads banner (https://developers.google.com/publisher-tag/reference). Virtuoso seems to handle well all of our content but when an Ads get render the scroll position get really flaky or the page just completely goes back up.

**Reproduction**
I tried to reproduced the issue without GPT for ease of understanding and because a good GPT setup require a lot of overhead. I ended up doing this sandbox which is not exactly like our issue but close enough. This sandbox seems to only get jumpy when scrolling back up, but in our case it both way.
https://codesandbox.io/s/vigilant-shockley-xx4nx?file=/pages/index.js

**To Reproduce**
1. Open sandbox
2. Scroll inside the page
3. Scroll back up and stop inside the page.

**Expected behavior**
I expected the list to play well with element that have an unknown size during render.

I know it get a bit complicated since the list is doing its best to handle the content dynamically. I would really liked to know if anyone had success rendering Ads banner or any content which is not available at render time using Virtuoso. Thanks for this awesome library

**Comment by petyosi** [comment]
You can check a thread several items below for expandable cards and scrolling up and down. Long story short - this is complicated, especially given the fact that you are using animations and stuff. There's a lot of logic that tries to preserve the scroll location at the correct place during upwards scrolling. Putting animations on top of it certainly won't be handled well. 

On a side note, putting cards with such dynamic behavior in a non-virtualized list won't be the best UX, IMO.

**Comment by frnk94** [comment]
Yea as I said the point is not to have Cards with such animation but to render Ads banner. I didn't put the whole Ads service in the example above. Our components which cause problems are Div which are loaded async and display an image banner for Ads purpose. I could maybe start working on a exemple to further show the error it just that it a bit complicated to get running in codesandbox.

**Comment by petyosi** [comment]
I guess you can certainly simulate that with some sort of a useEffect + setTimeout. Notice that the virtualized list unmounts the items when they are scrolled out of sight, not sure if this does not contribute to the problem as well. 

At any case, what you describe is hard to tackle - the list does not (nor cannot) compensate properly for asynchronous content size changing, mostly because there's no right or wrong choice to be made there.

**Comment by etienne-martin** [comment]
Thanks for the clarification @petyosi

If I understand correctly, the content size is calculated when an item is first mounted, and virtuoso will * not * accommodate size changes if the item changes dimensions * after * being mounted.

**Comment by petyosi** [comment]
No, that's not the case. It is perfectly fine to have changes like cards being expanded and collapsed with user interaction. However, content which inflates on its own due to loading cannot be handled in a graceful manner. I would go as far as saying that this is an UX anti pattern in general, with or without virtualization.

**Comment by etienne-martin** [comment]
I totally agree with you that having content shifting around (virtualized or not) is horrible for UX. It also causes browser reflows which can be bad for performance. The code sandbox that @frnk94 provided is not ideal, things are moving all over the place and you might be wondering why someone would want to do that.

To give you more context, here's what we're trying to achieve:

![image](https://user-images.githubusercontent.com/9700213/129406261-418afff2-4e2e-43e7-bbbf-259c6fdf17eb.png)

We have a list of rows holding content that's dynamic in height but doesn't change over time. The rows get measured by virtuoso just fine. The problem arise when we add ads in the lot. 

The ads are of varying height (driven by Google Ad Manager) so we can't know in advance how tall they are going to be. The ads are also loaded asynchronously so their height is only known a couple milliseconds _after_ being mounted. We display some sort of placeholder when the ad is loading so that the div containing the ad is not empty with a height of 0. Once the ad is loaded it jumps in size (there are no animations like in the provided code sandbox).

What's confusing to me is that I don't see how a change of dimension that is caused by a user interaction would be treated differently from one that's caused by an asynchronous event. 

I hope this clarifies what we're trying to do and I wonder if you think that's something we can achieve with Virtuoso.

I know debugging other people's problem for free is probably not your goal in life so we would be happy to pay you for your time if you think our use case is feasible with the current implementation of Virtuoso. 

Thanks for being super responsive by the way.

**Comment by etienne-martin** [comment]
> I would recommend that you can use something like an infinite loader instead, where the previous items are kept in the DOM.

One thing I didn't mention in my previous message is that our use case is similar to a twitter or facebook feed in that the goal is to render an indefinite amount of items (with ads). The infinite loader approach is what we implemented initially but it didn't scale performance-wise given the amount of items that were continuously being added to the DOM.

**Comment by petyosi** [comment]
@etienne-martin got it - let me try to help you further in that aspect. You can contact me at the email on my GH profile.
