### ISSUE TITLE
[BUG] 1.10.4 broke lists popping in a dialog with a zoom transition (error of Zero sized element)

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#433]
Hi @petyosi, hope you're doing well.  

**Describe the bug**
Since 1.10.4,  some of ours lists are broken and show the Zero sized element error when our Dialog is opened with a Zoom transition (material-ui dialogs).   Something that always worked up to 1.10.3

**Reproduction**
https://codesandbox.io/s/wizardly-gates-1s1n8
https://1s1n8.csb.app

**To Reproduce**
1. Open the dialog with Zoom transition.   
2. Opening with fade transition does not create the problem.

**Expected behavior**
A properly rendered list.

**Additional context**
If you select back 1.10.3, both dialogs work fine.  I'm guessing this commit might be responsible
https://github.com/petyosi/react-virtuoso/commit/392b9c8e717f9a937573c3db0a17d50d0d4a3132

If you can find a fix that would be incredible.  For now we'll lock to 1.10.3 as I wouldnt want to move just those dialogs to another transition.   

Your help is really appreciated
Thx

**Comment by petyosi** [comment]
The error is correct. You should find an alternative implementation on your side, for example, start the zoom from 10%. I am surprised that this worked before, probably due to offsetHeight being reported with random values for non-default zoom levels. 

To clarify further, the initial rendering cycle of the list happens at a zero-sized state. This can't work.

**Comment by Ethorsen** [comment]
I was afraid you would say that.  I'll try to mangle with the MUI transition to fix it.

Thanks!
