### ISSUE TITLE
[BUG] followOutput not always going to bottom when paging in data

### ISSUE THREAD

**Issue by agamrp** [petyosi/react-virtuoso#554]
**Describe the bug**
FollowOutput doesn't consistently go to the bottom the list when paging in data for a reverse scroll list.

More Context:
I am implementing a reverse chat list with infinite scroll. If the viewport is bigger than the initial page size of data I get from a remote API, I rely on the startReached to get more data asynchronously to fill the viewport. I try to use initialTopMostItemIndex and followOutput to keep the bottom of the list showing. Sometimes it does not work correctly (e.g. the last message is hidden). 

This happens using both 'smooth' and 'auto' behavior for the followOutput method.

If I instead give virtuoso the full list of data instead of paging in, it does go to the bottom of the list.

For the code sample below, I show the behavior using 'smooth' but switching it to 'auto' does seem to work for the sample. However hoping you can take a look since this still happens on my actual code using 'auto' and if you have any suggestions in case I'm doing something weird.

Thanks!

**Reproduction**
https://stackblitz.com/edit/react-fnqbh9?file=src/Chat.js

**To Reproduce**
1. Go to code sample
2. Click around on the chat buttons and you'll see sometimes the list doesn't scroll to the bottom

**Expected behavior**

**Screenshots**
https://user-images.githubusercontent.com/433174/152061474-a027da49-d9d8-41d3-8f2b-e17da13f1ec7.mov

**Desktop (please complete the following information):**
 - MacOs
 - chrome, firefox

**Comment by petyosi** [comment]
This example is quite convoluted, and I've had something similar on in a chat setup. In a nutshell, it relies on `startReached` being continuously called until the viewport is full of items because the page size is too small for that viewport. 

With that setup, I am seeing that new item sizes are reported at the *top* of the list, which should not happen - I am not sure why this is so, to be honest.

In general, I've never gone down the rabbit hole of examining that particular behavior (very small page size, filling in the viewport over multiple calls) because it's not very practical from a UX point of view. Bumping the page size to something like `50` has solved the setups I had. The example does not include adding new messages to the chat box, but I am sure it will work.
