### ISSUE TITLE
Specifying a different itemHeight per item/group?

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#59]
We have a GroupedVirtuoso list with known item heights.   But each item and group header has a different height.

Is it possible to achieve this using the itemHeight prop ?   Like passing a function instead of a number,  function that would take a group index or an item index and would return an itemHeight.

something like
```
<GroupedVirtuoso
itemHeight={(itemIndex) => number}
groupHeight={(groupIndex) => number}
/>
```

BTW. I cannot use the auto sizer feature, because most of my items have negative margins for imbrication/overlapping.

Thx

**Comment by petyosi** [comment]
Hey,

I would recommend looking into the autoSizer as an approach - the itemHeight and groupHeight are meant to be used for uniform size scenarios. 

You mention that you have negative margins that you use to visualise overlaps. Can I see that running somewhere? Changes are this scenario can be tuned to work as expected.

Cheers,

**Comment by Ethorsen** [comment]
I tried many different patterns, and can never get the auto sizer to figure out cell heights correctly as soon as a negative margin is specified.

I'll try to reproduce in a sandbox

**Comment by Ethorsen** [comment]
I was able to get this thing working for us.   Instead of using negative margins for interlace,  I'm now using fixed height with visible overflow.  In terms of positioning a scrolling,  it now works fine. 

But I still have a visual bug that I cant figure out.   When scrolling slowly,  the first element on the screen sometimes appear after it entered the viewport or disappear before it exits the viewport.

To demonstrate, I created a stripped down version of the thing in this sandbox. This will give you a basic idea of what we're trying to achieve (some timeline with events alternating left and right)
https://codesandbox.io/embed/vigorous-heisenberg-c1irs?fontsize=14&hidenavigation=1&theme=dark

You'll notice, if you scroll slowly up and down, that the first item is jumping in and out before exiting or entering the viewport.

I tried playing with the overscan prop but it doesnt seem to make any difference.

Please let me know if you can help me figure this out.

**Comment by petyosi** [comment]
Thanks for the repro, I believe I know what's going on. 

When I designed the groups, I assumed that the sticky group headers would be *non-transparent* and occupying the full width of the list viewport. As soon as something passes the bottom border of the group, the code considers it invisible and removes it from the list of items. Removing the width of the group element addresses the problem partially. 

By partially, I mean that you will still see the "forced height" items appear later than they should because the component considers them shorter than what they are. There is not much to do about it I'm afraid - I would direct you to the Virtuoso Grid component, but it does not support grouping (and it would be very complicated, to get it right). 

I am sorry for not being to help further. What you're trying to achieve - a two-sided overlapping timeline - seems like a very specific use case that I never had in mind when designing the component.

**Comment by Ethorsen** [comment]
Thanks for taking a look.

Even if its an edge case, I feel we're not far from having this thing work as expected.

I tried to do the opposite, and have the overflow pop above the actual line.  But unfortunately it gives the same problem but for the item at bottom of the list.

Correct me if I'm wrong, but isnt the overscan prop used to actually render more items than whats required on screen?  If they were already rendered, lets say 500px before entering viewport, they would already be there?

**Comment by petyosi** [comment]
What you say sounds right - I will revisit the tests and see if the overscan is actually included in the grouped mode. Flagging it as a bug for now.

**Comment by Ethorsen** [comment]
Thx

**Comment by petyosi** [comment]
@Ethorsen I found the culprit. I will look into a few other issues and release an update during the weekend.

**Comment by petyosi** [comment]
Hey @Ethorsen, [updated your example](https://codesandbox.io/s/hopeful-violet-4ktse) to the latest version - it seems to work as expected. Cheers.

**Comment by Ethorsen** [comment]
Yes, working nicely and as expected since 12.6.   Thx a lot
