### ISSUE TITLE
[BUG] Visual problem while using Virtuoso with OverlayScrollbars, introduced in 2.3.2

### ISSUE THREAD

**Issue by Ethorsen** [petyosi/react-virtuoso#662]
Hi @petyosi 

**Describe the bug**
In 2.3.2, when using with OverlayScrollbars as custom scrollbar.  Items not initially in the viewport wont render/show.

**Reproduction**
https://codesandbox.io/s/react-virtuoso-custom-scrollbar-forked-jfdu5y?file=/src/CustomScrollbar.js

**To Reproduce**
Simply scroll down, items passed initial viewport are showing blank.

![image](https://user-images.githubusercontent.com/1493968/168886238-db303f98-99a8-424e-89e6-cf2c21409aa5.png)

Switching to 2.3.1, items are loading fine

**Expected behavior**
Items loading properly

**Screenshots**
![image](https://user-images.githubusercontent.com/1493968/168886326-3dfbdb01-3d81-419a-a1c9-f3db0b9b2aef.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

Thx

**Comment by petyosi** [comment]
This (and the other issue you have reported) is due to this additional size change detection introduced [in 2.3.2](https://github.com/petyosi/react-virtuoso/blob/2a1131ad84997ed94947324077c61316ac908c85/src/hooks/useChangedChildSizes.ts#L17-L19). It boils down to the component searching for an element with `data-virtuoso-scroller` attribute. 

I have no knowledge of the third-party library you refer to, so I can't assist with the exact solution to this problem. However, the custom scroll component receives [the data attribute through its props](https://github.com/petyosi/react-virtuoso/blob/2a1131ad84997ed94947324077c61316ac908c85/src/List.tsx#L357-L369) - you should be able to adjust it.

**Comment by Ethorsen** [comment]
Thx @petyosi 

Made this sandbox fixing the crash.  But i'm left with the problem mentioned here (additional data is never loaded).

https://codesandbox.io/s/react-virtuoso-custom-scrollbar-forked-6wynfm?file=/src/CustomScrollbar.js

I'll schedule a different task for us to upgrade and investigate/fix this issue.

If you ever have a few minutes to check it out that would be appreciated.  Maybe the solution will be obvious to you. (the data-virtuoso-scroller attribute might not be applied to the right element)

Take care
