### ISSUE TITLE
[BUG] Prepend remounts items

### ISSUE THREAD

**Issue by thomassuckow** [petyosi/react-virtuoso#663]
**Describe the bug**
When prepending items (even when not scrolling):
1. all the current items on the screen are unmounted
2.  a similar number of items from the beginning of the array are mounted (with the correct indexes passed to the itemContent method)
3. those items are then unmounted
4. the original items (plus any new ones appropriate for the scroll position and overscan with increaseViewportBy) are mounted 

**Reproduction**
https://codesandbox.io/s/sandpack-project-forked-nfh26g

**To Reproduce**
1. Go to https://codesandbox.io/s/sandpack-project-forked-nfh26g
2. Scroll up to the top
3. Note the number of times the item has been mounted
4. Wait for loading to finish after 500ms
5. Note the number of times mounted increased

Alternative Steps:
1. Go to https://codesandbox.io/s/sandpack-project-forked-nfh26g
3. Note the number of times the item has been mounted
3. Click "Load More"
4. Note the number of times mounted increased

**Expected behavior**
The number of times an item has been mounted should only increase while it is outside the viewport

**Screenshots**

https://user-images.githubusercontent.com/3100037/168894812-f73f9bb9-6e3a-4737-a064-5c4223fd53f4.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Chrome 101.0.4951.64 (Official Build) (x86_64)

**Additional context**
Having a header component or not seems to have no effect.

On larger lists with React18 this causes flashes of "white" because the elements disappear and then appear again. But also reproduces on react 17.

**Comment by petyosi** [comment]
This is a good catch, and, indeed, something which would be great to avoid. It's not so easy though, as prepending items quickly scrolls down/restores the position of the list, causing the effect you observe.

**Comment by thomassuckow** [comment]
Would allowing the browser to manage layout shift possibly mitigate this? Though I assume you banish the browser handling that for good reason.

**Comment by petyosi** [comment]
Do you refer to the `overflow-anchor: none` applied? As far as I have seen, what the browser does is more of a best-effort rather than something to rely on. It also varies across browsers, as far as I remember.

**Comment by petyosi** [comment]
@thomassuckow I think I got that done in that release, but please help me by verifying it.

**Comment by petyosi** [comment]
@paulincai No, this should not be a breaking change or change in code required. Replicate the problem in a sandbox. I will take a look.

**Comment by paulincai** [comment]
@petyosi unfortunately I cannot replicate this because I cannot replicate my environment. I may try to explain it a bit.

In the default sandbox (from your website example) you have START_INDEX of 10.000 and then you add 100 items.
As per the further behavior of the component, I believe once the items are loaded, your firstItemIndex should be 10.000 - 100 because START_INDEX corresponds to an empty users array and as you add items your firstItemIndex  decreases by the number of items. In the example, the first batch of users adds beyond the START_INDEX (e.g up to 10.100.) I would expect at this stage to have START_INDEX = 9900 and the last index in the list to be 10.000. No other option worked for me most probably because of the asynchronicity.

It doesn't feel like there is any problem when you are in the example because everything is synchronous. If I had to implement the exact example provided by your website with asynchronous functions and wait for my items to arrive from the server, the example would not work. I cannot do a ``` setFirstItemIndex``` in ```prependItems``` cause this only works synchronously for your example. In most cases that needs to happen in a useEffect. One of the problems is that if I set the firstItemIndex before I received the new items, I can see the list flickering (going up and down quickly). Then I need to wait for my items, take a count and then calculate the new firstItemIndex.

What changed from 2.13.0 to 2.13.1 is that this effect (useEffect) no longer works as before:

I need to wait for my messages to arrive. The initial pull, as well as the rest of the pulls, is a maximum of 20 messages so I am on the "else" side of the "if".
Upon scroll up and reach the top of the list, a new pull is done and I am on the first side of the "if" condition. The problem is that I have to wait for the length before I set the new initial index. Even if I know the length in advance, I still need to wait for the items to be received and renderable.

```
useEffect(() => {
    if (messages?.length) {
      if (messages?.length > 20) { // this is the batch size I pull from the server.
        setFirstItemIndex(START_INDEX - messages?.length)
      } else { // on false, I reach here because I probably do the first pull. I just entered the chat window and pull the first 20 messages.
        setFirstItemIndex(START_INDEX - 20) // In the old version this worked fine.
      }
  }, [messages?.[0]?._id, messages?.length]) // if I have a valid message or a change in the length of messages


const prependItems = useCallback(() => {
    dispatch(callGetMoreMessages(Math.max(messagesLimit, messages?.length || 0) + nextLimitMessages)) // I use Redux and the result of this comes as a prop (useSelector). A change in the length of this prop triggers the useEffect above
    return false
  }, [firstItemIndex, messages?.length])

```

... after further tests. The same code as above but I wrapped the else in a setTimeout and I get all messages of the initial pull. The problem described in my initial message is no longer a problem. However, now the difference between 2.13.0 and 2.13.1 is that in 2.13.1 I get a flicker when new items are being pulled. It does not go up and down it just disappears for a fraction of a second (maybe couple of milliseconds but clearly visible). When back to 2.13.0 and everything is smooth like ... PERFECT.

```
 if (messages?.length) {
      if (messages?.length > 20) {
        setFirstItemIndex(START_INDEX - messages?.length)
      } else {
        setTimeout(() => setFirstItemIndex(START_INDEX - 20), 0) // here is the change.
      }
  }
```

I am sorry if this is not of much help, I feel it is the most I can explain. I am open to a quick remote into my station in the coming days at your most convenient time fi you wish.

**Comment by paulincai** [comment]
Ok all said above were on React 17.0.2. React 18 makes it even worse. The flickers are very proeminent. Tried React 18  with both 2.13.0 and 2.13.1 and the behavior is similar. Will need to go back to React 17.0.2 and 2.13.0 if this library. These are the last versions that worked perfectly.

**Comment by petyosi** [comment]
@paulincai I can't help without a repro. And yes, changing the `firstItemIndex` and the change of `data` (or total count) *must* be synchronous. Itherwise there would be flickering for sure.
