### ISSUE TITLE
totalListHeightChanged reporting imprecise values on rows with fractional pixel heights

### ISSUE THREAD

**Issue by cmattick** [petyosi/react-virtuoso#680]
I am using totalListHeightChanged for showing a list in a popup without scroll bars if there is enough space. To get rid of the vertical scrollbar it is necessary to get precise fractional values. Since my row heights may have fractional pixel values the scrollbar is shown sometimes if i use totalListHeightChanged for my calculations (setting the scroll container height to the value provided by totalListHeightChanged).

Is there a reason why I can't expect fractional values in the height parameter of totalListHeightChanged? Or is this a bug?

**Comment by petyosi** [comment]
I found out why I had to revert back to rounding numbers - #446. The problem is that you can't scroll to a fractional value 😢.

At any case, if the problem in that issue does not apply to you, you can use `itemSize` [like this](https://codesandbox.io/s/sandpack-project-forked-nil4l0?file=/App.js). Of course, you can also figure out how to avoid fractional values (which I usually recommend if possible).

**Comment by cmattick** [comment]
Thanks alot for clarification and the suggestions!
