### ISSUE TITLE
[Feature request] pull to refresh

### ISSUE THREAD

**Issue by AyumiKai** [petyosi/react-virtuoso#7]
hi, @petyosi , do you want to add pull refresh?  I really need this feature right now, and probably others too  :)

**Comment by petyosi** [comment]
Hey, @AyumiKai - Supporting pull to refresh is possible, indeed.  I think I would rather keep the pull/release/refresh logic external to the component, though. 

Some thoughts: For this to work, I guess the virtuoso component should support optional header render prop (just like the footer), and maybe, ref access to the scroller element so that touch events can be bound to it. 

I am not sure when / if I will be able to get to that feature - feel free to examine the source code and give it a try.

**Comment by FezVrasta** [comment]
Support for `header` prop just like `footer` would be very welcome!

**Comment by AyumiKai** [comment]
> Hey, @AyumiKai - Supporting pull to refresh is possible, indeed. I think I would rather keep the pull/release/refresh logic external to the component, though.
> 
> Some thoughts: For this to work, I guess the virtuoso component should support optional header render prop (just like the footer), and maybe, ref access to the scroller element so that touch events can be bound to it.
> 
> I am not sure when / if I will be able to get to that feature - feel free to examine the source code and give it a try.

**Comment by AyumiKai** [comment]
header render prop, that is good idea

**Comment by petyosi** [comment]
@AyumiKai I just published v0.5.0 which provides access to the scroll container DOM element - I think it should be possible to plug pull to refresh logic through that. Check [the example](https://virtuoso.dev/custom-scroll-container).
