### ISSUE TITLE
Scrolling issue in GroupedVirtuoso with defined GroupContainer property (iOS)

### ISSUE THREAD

**Issue by tschortsch** [petyosi/react-virtuoso#72]
Related to this issue #70 there still seem to be a scrolling issue in the `GroupedVirtuoso` component. When there is a custom `GroupContainer` defined and a function which changes the state of the component (like `scrollingStateChange`) there is a scroll jump happening when reached the top of the list. See this example implementation: https://codesandbox.io/s/groupedvirtuoso-scrolling-issue-04l0y / https://04l0y.csb.app/ (mobile view to reproduce the bug on an iOS device)

Screen record: https://vimeo.com/392226942

Setup:
* react-virtuoso v0.13.2
* iOS 13

**Comment by petyosi** [comment]
Hey @tschortsch, check v0.13.3 - it fixed the problem in my tests.

**Comment by tschortsch** [comment]
The fix works great, but I just found out there there also seem to be a little issue at the bottom of the `GroupedVirtuoso` list (sorry for not noticing earlier 😓). I again reproduced it in this example: https://codesandbox.io/s/groupedvirtuoso-scrolling-issue-04l0y / https://04l0y.csb.app/ (mobile view to reproduce the bug on an iOS device)

Screen record: https://vimeo.com/393618810

Setup:
* react-virtuoso v0.13.3
* iOS 13

**Comment by petyosi** [comment]
The behavior is improved in v0.13.5 - check [this sandbox fork](https://codesandbox.io/s/groupedvirtuoso-scrolling-issue-twwc0). It is not perfect; if you pull at the bottom and keep it pulled for a while, you will see a blink (because of the isScrolling state change). 

Detecting this is going to be quite messy TBH, because you have to detect touch events and so on.
