### ISSUE TITLE
Scrolling down will jump to previous scroll to index  

### ISSUE THREAD

**Issue by pedroalves0** [petyosi/react-virtuoso#75]
After the `scrollToIndex` method is used to set the list visible start item, scrolling down a certain amount will jump to the last scrolled to index. This is apparently due to the list height changing by the rendering of a new item when scrolling down.

The behavior can be observed even in `react-virtuoso`'s examples - https://virtuoso.dev/scroll-to-index/ - notice how scroll will jump back to item `500` after reaching `506`:

![scrolltoindex](https://user-images.githubusercontent.com/3800074/75552121-81724800-5a2d-11ea-95fc-6c064700020b.gif)

Package version: 0.13.1
Browser: Chrome v79.0

**Comment by petyosi** [comment]
Thank you for the report, I think this is a regression I introduced (had similar problem at some point). Will look into it.

**Comment by petyosi** [comment]
I will test this further before releasing the new version.

**Comment by pedroalves0** [comment]
Thanks for looking into it @petyosi . I've tested your fix and I no longer experience the scroll to last index issue 👌

That said, I found a new issue, when jumping to an index and scrolling up it there will be a lot of jitteriness, I guess because new items are being measured and rendered on top, so the current top item gets pushed down a bit. Higher overscan values seem to alleviate this issue, but if the index is higher than this threshold then it becomes very obvious. In the example page it's less noticeable because one can scroll multiple items before a new item is rendered on top, but it's still there:

![scrollbackjump](https://user-images.githubusercontent.com/3800074/75663694-29c02080-5c69-11ea-8e35-7043c8693b17.gif)

**Comment by petyosi** [comment]
@pedroalves0 This is a problem which I don't know how to address - yet. Let me explain (using the example page). 

When jumping to the 500th item, the heights of the items above are unknown, so the component assumes the default value (the 1st item height or `defaultItemHeight`). As you scroll up, the top of the list is changed and the skipped items are inserted, with the assumption that their height is the default one. If it's not, then a readjustment is necessary, otherwise, the list will visibly jump. 

This readjustment however, is visible - this is the slight jump visible in your screen recording. 

Again, I don't know how to solve this clearly. A "pre-measurement" step means double rendering, which I would like to avoid as it will be a noticeable performance regression for the "default" scrolling direction. 

Hope this makes sense - thank you very much for your thorough bug reports!
