### ISSUE TITLE
[BUG] GroupedVirtuoso destroy group's items when not visible with overscan

### ISSUE THREAD

**Issue by theofournier** [petyosi/react-virtuoso#781]
**Describe the bug**
Hey, thank you for this awesome package!

I noticed when using a `GroupedVirtuoso` component with `overscan` and `increaseViewportBy` props, scrolling down will destroy all group's items when group is outside viewport without taking into account the props.

Thanks for your support

**Reproduction**
Code Sandbox: https://codesandbox.io/s/shy-voice-n6plzm?file=/src/App.js

**To Reproduce**
1. Open the console
2. Scroll down the grouped list until the Group 1 becomes invisible
3. See on the console that all items of Group 1 has been destroyed

**Expected behavior**
The `GroupedVirtuoso` should take into account the props `overscan` and `increaseViewportBy` between groups.

**Screenshots**
Here is a recording of the Sandbox, reproducing the issue:

https://user-images.githubusercontent.com/25389865/199095518-55f3fceb-6966-4b8d-85b4-793b7990d55e.mov

**Desktop**
 - OS: MacOS Monterey (12.6).
 - Browser: Chrome

**Comment by petyosi** [comment]
The behavior you describe is I believe not related to not honoring overscan, but due to how stickiness works. Sticky groups are moved to the top item container, which causes their re-creation. 

Fixing this is possible in theory but needs an overhaul of the rendering logic, something I am not looking into doing in the foreseeable future.
