### ISSUE TITLE
[BUG] Initial item count broke VirtuosoGrid 

### ISSUE THREAD

**Issue by alexanderoskin** [petyosi/react-virtuoso#801]
**Describe the bug**
Since v3.0.0 if you set initialItemCount parameter in VirtuosoGrid scroll will jump every time after new data added to the grid data.

**Reproduction**
Minimal reproduction https://codesandbox.io/s/virtuoso-ohhicm

**To Reproduce**
1. Go to https://codesandbox.io/s/virtuoso-ohhicm
2. Try to scroll list

**Comment by petyosi** [comment]
That's a bug indeed, had to modify the sandbox to reduce the initial item count, though (https://codesandbox.io/s/virtuoso-forked-npj7tc?file=/src/App.js).

**Comment by alezen9** [comment]
+1
@petyosi I'm experiencing a similar issue if not the same but with Virtuoso component, using `initialItemCount` for ssr purpose but then the endReached never fires to fetch and append more items on scroll.
Is there a temporary workaround using virtuoso apis that you can suggest in the meantime?
Thanks :)

Here is my usage
```typescript
<Virtuoso
  style={{ minHeight: 100, width: '100%' }}
  data={list} // internal state includes the whole list of items
  useWindowScroll
  endReached={loadMore} // fn that fetches the next page and appends it to the "list"
  initialItemCount={firstPage.length} // coming from server -> props
  itemContent={...}
  components={...}
/>
```

**Comment by petyosi** [comment]
@alezen9 I am happy to examine your case and ensure that it works as expected. Let me know once activate the [sponsorship subscription](https://github.com/sponsors/petyosi/sponsorships?sponsor=petyosi&tier_id=50934&preview=false).

**Comment by DavoCg** [comment]
Hey @alezen9 I had the same issue as you have, from my understanding its because the initial rendering render all items specified by `initialItemCount` and because the last item is rendered once, `endReached` is not triggered anymore. I found a simple fix in gridSystem.ts 

```javascript
  const endReached = u.streamFromEmitter(
      u.pipe(
        u.duc(gridState),
        u.filter(({ items }) => items.length > 0),
        u.withLatestFrom(totalCount),
        u.filter(([{ items }, totalCount]) => items[items.length - 1].index === totalCount - 1 && items.length !== totalCount),
        u.map(([, totalCount]) => totalCount - 1),
        u.distinctUntilChanged()
      )
    )
```

this condition ``` && items.length !== totalCount``` will ensure `endReached` is not triggered at initial rendering. 

I don't think this is an optimal fix, I can safely use it because I'm always sure rendered items count will always be inferior to initialItemsCount.

Thanks @petyosi for this amazing lib
