### ISSUE TITLE
[BUG] ResizeOvserver loop limit exceeded - webpack-dev-server related

### ISSUE THREAD

**Issue by martinchrzan-workday** [petyosi/react-virtuoso#875]
**Describe the bug**
After upgrading to 4.2.0 (upgraded from 4.0.9), I am getting this error locally immediately on loading React-Virtuoso component
It seems like I can just close this error overlay, but it always come back as I scoll in the list and load new items.

**Reproduction**
Happens immediately upon landing on the react-virtuoso component

**Expected behavior**
Not getting the error.

**Screenshots**
<img width="424" alt="Screenshot 2023-04-05 at 13 39 35" src="https://user-images.githubusercontent.com/93981583/230070288-15090183-8996-48e0-aca4-5e8459d32b6b.png">

**Desktop (please complete the following information):**
 - OS: MacOS.
 - Browser: Chrome

**Comment by petyosi** [comment]
I need a reproduction to fix this. In general, this error is to be ignored, but I can't say if there's something else happening. Can you isolate in a sandbox?

**Comment by petyosi** [comment]
@martinchrzan-workday - did you find something? Let me know once you get to that.

**Comment by dylanwulf** [comment]
Hi @petyosi @martinchrzan-workday, I was able to reproduce the issue here: https://github.com/dylanwulf/virtuoso-error.
All I did was fork the "Endless Scrolling" demo from the react-virtuoso docs and I updated react-scripts to the latest version. Just run the reproduction and keep scrolling to the bottom. It doesn't show the error 100% of the time but it does eventually show up.

**Comment by iamterryclark** [comment]
Hey there,

I also have this issue,

using React 17.0.2 with electron, I found that react-virtuoso was the issue even I updated to 4.2.1 , even after the memo fix. 

This is just a debug issue and not in production.

I see using the use memo on the resize observer inside useSizeWithElRef and  wrapping a requestAnimation function on the data works well. the information came from here

https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded/58701523#58701523

line 467 in your index.mjs i am now doing this

```js
return new ResizeObserver((entries) => {
  // We wrap it in requestAnimationFrame to avoid this error - ResizeObserver loop limit exceeded
  window.requestAnimationFrame(() => {
    if (!Array.isArray(entries) || !entries.length) {
      return;
    }
    // your code
    const element = entries[0].target;
    if (element.offsetParent !== null) {
      callback(element);
    }
  });
});
```

**Comment by petyosi** [comment]
@iamterryclark My guess is that some development mode utility is eagerly catching this error and promoting it when it should not. Something similar was happening with react-beautiful-dnd.

Regarding your suggestion: unfortunately, I've tested the route of `requestAnimationFrame` and ultimately had to revert it for multiple reasons, performance lag being one of them. 

If you can reproduce the problem in something I can run, it will help me help you a lot. Electron is not my jam, though.

**Comment by petyosi** [comment]
@iamterryclark Forgot to mention - notice that v4.2.1 does not fix this problem :) but something else I discovered while testing. Right now, I believe it's a setup problem, not something that can be addressed from within the component (unfortunately).

**Comment by iamterryclark** [comment]
sorry missing character ^^ edited

ill try this locally also and see if I can get a reproducible example

**Comment by dylanwulf** [comment]
Some more info I found: looks like this error started showing up with `webpack-dev-server` v4.12.0 https://github.com/webpack/webpack-dev-server/issues/4771. They added a config option to hide it

**Comment by martinchrzan-workday** [comment]
Thanks for the investigation, I can confirm that `webpack-dev-server` was the culprit of this issue. Using their new config to hide runtime errors fixes the issue

**Comment by petyosi** [comment]
Folks, thanks for your help here, it looks like there's not much that can be done on the component level. If someone finds something different, let me know.

**Comment by mankittens** [comment]
It appears this bug has popped up again in v4.7.0. It does not present in v4.6.3 for me.

**Comment by petyosi** [comment]
@mankittens I will need a bit more from your side, there are several different topics discussed in this issue. Can you can open a new one with a reproduction?

**Comment by Arkellys** [comment]
I've just installed this library and noticed this error too. In my case, I use `webpack-dev-server`, so I guess it's nothing new. The workaround I have in my code is to use a [ponyfilled version](https://github.com/juggle/resize-observer) of `ResizeObserver` in development:

```js
if (isInDevelopment) {
  global.ResizeObserver = (await import("@juggle/resize-observer")).ResizeObserver;
}
```

I'm actually using this because I also have a bug with another library using `ResizeObserver` and the ponyfill fix it. I only noticed the resize loop error because I was doing some refactoring and temporarily commented out the workaround.

In the docs of [`@juggle/resize-observer`](https://github.com/juggle/resize-observer), it's mentionned it has a [resize loop detection](https://github.com/juggle/resize-observer?tab=readme-ov-file#resize-loop-detection), which prevents the loop error to be dispatched. I guess it's an alternative for those who don't want to change their dev server configuration.

**Comment by trainoasis** [comment]
We had to revert `react-virtuoso` from `4.7.1` to `4.6.3` to make this work, otherwise our Cypress tests are failing with ResizeObserver errors (even if handled in Cypress and ignored, it then fails with memory issues). 

Is there anything specific that we can fix in the app to avoid this?

**Comment by nowaylifer** [comment]
> We had to revert `react-virtuoso` from `4.7.1` to `4.6.3` to make this work, otherwise our Cypress tests are failing with ResizeObserver errors (even if handled in Cypress and ignored, it then fails with memory issues).
> 
> Is there anything specific that we can fix in the app to avoid this?

same

**Comment by petyosi** [comment]
@trainoasis @nowaylifer Did any of you bring this to Cypress?
