### ISSUE TITLE
[BUG] Poor scroll performance in Chrome when items are links

### ISSUE THREAD

**Issue by dzucconi** [petyosi/react-virtuoso#877]
When the items are links Chrome will drop frames. This is likely a browser bug worth reporting, but I'm having trouble characterizing it. You'll notice that if you pay attention to the link status bar on the bottom left of the screen: in the [virtual grid example](https://codesandbox.io/s/scrollable-virtual-grid-with-links-3g2pez) it updates frequently as you scroll. In the [non-virtual grid example](https://codesandbox.io/s/scrollable-normal-grid-with-links-om3r49) it only updates on mouse movement.

**Reproduction**
[Scrollable virtual grid with links](https://codesandbox.io/s/scrollable-virtual-grid-with-links-3g2pez) vs [Scrollable non-virtual grid with links](https://codesandbox.io/s/scrollable-normal-grid-with-links-om3r49)

**To Reproduce**
1. Scroll the page with your mouse hovering any of the links

**Expected behavior**
Both Safari and Firefox have smooth scroll performance without frame drops

**Desktop (please complete the following information):**
 - OS: OSX 12.6.3
 - Browser: Chrome 111.0.5563.146

**Comment by dzucconi** [comment]
Upgrading to Chrome 112 seems to have fixed this! Closing.

**Comment by petyosi** [comment]
Hm, my Chrome has not updated to 112 yet, and I don't experience any performance degradation in the example. There's a chance I am missing something - I am trying to reproduce by swooshing on an Apple trackpad so that I can see if the inertia gets choppy. 

In the past, I've seen certain browser extensions that do fancy stuff on the DOM (Grammarly, for example), having a slight performance hit on the component's performance. However, I use grammarly myself and it does not cause frame drops.
