### ISSUE TITLE
[BUG] `VirtuosoGrid` + CSS Grid `List` component: items not rendered

### ISSUE THREAD

**Issue by psychedelicious** [petyosi/react-virtuoso#889]
**Describe the bug**
Conditions:
- use`VirtuosoGrid`
- use a `List` component that is a CSS grid using `gridTemplateColumns` (eg `grid-template-columns: repeat(auto-fit, minmax(100px, 1fr))`
- the client's zoom setting is not 100%
- the window/container is resized to certain widths

Result:
The rendered list's `paddingBottom` is occasionally miscalculated, resulting in a number of items not rendering in the window. It seems `paddingTop` does not get miscalculated, or its error is far less severe.

**To Reproduce**
1. Go to https://codesandbox.io/s/sandpack-project-forked-5slkdt?file=/App.js
2. Increase or decrease the browser zoom, say 120% (may need to try other zoom levels)
3. Very slowly resize the window horizontally and note when `paddingBottom` value abruptly jumps and items are rendered at a significant offset to where they should be.

**Expected behavior**
Items are always rendered in the window correctly.

**Screenshots**
Using the CSS grid visualiser helps to show the issue.
https://user-images.githubusercontent.com/4822129/235429456-19a09795-f0d9-474d-bfd0-306c446cd033.mov

**Desktop (please complete the following information):**
 - OS: macOS, windows
 - Browser: FF, chrome

**Additional context**
I'm happy to try to fix this, but I'm not 100% sure where to dig into the code. Can you point me in the right direction?

**Comment by petyosi** [comment]
Thanks for the report. Looking at the example, I believe that we're facing a floating number edge case, where the calculation of how many items will fit into the width of the container is incorrect. From your clip, I am certain that's happening because of the "last item missing" state.

I will try to look at this, but due to life, it might take me a while to get on top of it. I am happy to accept a PR of course. You can give this a shot by modifying one of the examples in the `exmaples/` dir to fit the case, and then poke the [`itemsPerRow` function](https://github.com/petyosi/react-virtuoso/blob/ec97e6fa97a53c825dee3605e721ffeb6042c25d/src/gridSystem.ts#L352).

**Comment by psychedelicious** [comment]
PR'd a fix
