### ISSUE TITLE
[BUG] react-virtuoso unmount item when it increase its height

### ISSUE THREAD

**Issue by ocavue** [petyosi/react-virtuoso#920]
**Describe the bug**

When one list item in the virtual list increase its height a lot, react-virtuoso will unmount this item. 

**Reproduction**

https://stackblitz.com/edit/vitejs-vite-a6xszn

This simple demo is an infinite list of editors. Each editor has a unique `<h1>` heading and a contentediable area. When typing in the editor, the content will be saved in a global store, so the conte won't be lost after unmounted.

**To Reproduce**
1. Go to the Stackblitz link above 
2. Scroll to *Editor 10*
3. Copy 100 lines of text from somewhere
4. Paste them into *Editor 10*
5. Now the list scrolled into *Editor 16*, and *Editor 10* is unmounted (and thus lose the focus)

**Expected behavior**

The list will scroll to the bottom of *Editor 10*, or the top of *Editor 11*. *Editor 10* should not unmount itself. 

**Screenshots**

https://github.com/petyosi/react-virtuoso/assets/24715727/0cef6cdc-fb19-43fc-a674-07dd3d0c9e0a

**Desktop (please complete the following information):**
 - OS: macOS 13
 - Browser: Chrome 114

**Comment by petyosi** [comment]
I don't have any idea on how this can be fixed or worked around, but I believe that I know what's going on - pasting the content causes the browser to scroll the list to **where the caret should be**. This happens before the changed size of the item gets reported. The component receives a scroll event and unmounts the item, since as far as it is concerned, the item is out of sight.

This is super esoteric, and my gut feeling is that it can't be fixed unless "playing god" and intercepting pastes - not something that the list should do, though. While I can keep this open, I honestly have no idea how can this be fixed on the list site, so I don't want to give you false hopes. 

Let me know if I am wrong in my assumptions, happy to discuss further in case. you know more.

**Comment by ocavue** [comment]
Thanks for your quick response. 

---

> This happens before the changed size of the item gets reported. The component receives a scroll event and unmount the item, since as far as it is concerned, the item is out of sight.

I have a naive idea: Can we get the correct size if we wait for a bit (let's say, 20ms) after receiving the scroll event and before doing unmount? I have no knowledge about react-virtuoso implementation, so I don't know whether or not this is doable or suitable. 

--- 

As for workaround, I did find that adding `overscan={{main: 2500, reverse: 2500}}` can resolve the 100-lines pasting. But pasting 200-lines would still cause issue. It's not perfect but at least can cover some common scenarios. What do you think about this workaround? Will such large `overscan` cause performance issues?

**Comment by petyosi** [comment]
Unfortunately delaying the unmount is not feasible unless the internal state management is reimplemented. Right now, mount/unmount are one operation - the list reacts to the position change and returns the visible items. Unmounting is a side effect of that. Delaying the reaction to the scroll event would cause the list to "lag" with empty contents when scrolling around, as this will delay the mount, too. As you can imagine, this is not an acceptable behavior for the component. 

The workaround you've discovered is the only realistic solution. As far as virtuoso itself, such values are not a problem (they are in pixels, btw, so that's several screens, basically). It all depends on the kind of components you have in each item, as having heavy/complex/memory intensive components in there can affect the performance.

**Comment by ocavue** [comment]
> It all depends on the kind of components you have in each item, as having heavy/complex/memory intensive components in there can affect the performance.

Unfortunately, we have quite a heavy editor component, so this seems to be bad idea for performance.

--- 

I tried the sleeping strategy by wrapping the scroll event listener with `setTimeout(..., 0)`. This seems to work quite well based on my limit test. 

*origin code*:

https://github.com/petyosi/react-virtuoso/blob/896bdaf40ce5939eab3b3adca37fa023875d37fc/src/hooks/useScrollTop.ts#L57-L68

*modified code*:

```ts.diff
  React.useEffect(() => {
    const localRef = customScrollParent ? customScrollParent : scrollerRef.current!

    scrollerRefCallback(customScrollParent ? customScrollParent : scrollerRef.current)
    handler({ target: localRef, suppressFlushSync: true } as unknown as Event)
-    localRef.addEventListener("scroll", handler, { passive: true });
+    const handlerLazy = (event) => setTimeout(() => handler(event), 0)
+    localRef.addEventListener("scroll", handlerLazy, { passive: true });
     return () => {
       scrollerRefCallback(null);
-      localRef.removeEventListener("scroll", handler);
+      localRef.removeEventListener("scroll", handlerLazy);
    }
  }, [scrollerRef, handler, scrollerElement, scrollerRefCallback, customScrollParent])
```




Now I can paste no mater how many lines of text and my editor won't unmount itself. Here is the [code](https://stackblitz.com/edit/vitejs-vite-jrp2s1?file=patches%2Freact-virtuoso%404.3.9.patch) and a video recording:


https://github.com/petyosi/react-virtuoso/assets/24715727/08d13516-7fea-40e2-858f-19e5cd44c743


In addition of the "'lag' with empty contents" issue you mentioned earlier, do you think this strategy has other potential downside? 

(Also, correct me if I'm wrong, I guess the lag can be partially reduced by setting `overseen` or `increaseViewportBy`)

If the only downside is the mount lag, then I think this would be a good workaround for us. Since in our case, a correct behavior (i.e. the editor should not lose the focus after pasting text) is more important than a smooth UI.

**Comment by petyosi** [comment]
To answer honestly - I don't know if there could be something wrong. This changes the timing of the scroll reporting events, so it might result in some edge cases not working as expected. At some point, there was a variation of what you're doing (with a requestAnimationFrame), and it caused bugs in reverse scrolling mode, so I had to revert it.

I pinged Alex over email, as I believe that there's a way to make your scenario work without any tradeoffs, but it will take me a while to explore and test that properly. Happy to do so if you decide to support the project.
