### ISSUE TITLE
[Question/Bug] CSS Transition animation not working with VirtuosoGrid

### ISSUE THREAD

**Issue by aakashnand** [petyosi/react-virtuoso#96]
### Problem
I am trying to use VirtuosoGrid to render a large grid using a material-ui library similar to the demo example from documentation [page](https://virtuoso.dev/grid-responsive-columns/). I want to expand the Paper component width on click of a button using CSS transitions but it is not working with VirtuosoGrid component however it works fine if the item is not rendered using VirtuosoGrid.

### Reference
I have created stackblitz app to show a demo. The bottom card works fine but the top card which is rendered using VirtuosoGrid does not work.
https://stackblitz.com/edit/react-virtuoso-animation

**When running for the first time, please change the transition-delay to any value from styles.css  otherwise the demo does not work for some weird reasons**

I am not sure if this is a bug in the library but any help on this would be highly appreciated.

**Comment by petyosi** [comment]
No idea on this. As far as I can see in the inspector, the elements are blinking, which probably suggests that rather than toggling a class, the code replaces the element, which won't cause a transition. 

Feel free to investigate this further - I am open to PRs. The code of the grid is tiny and simple compared to the list one.

**Comment by aakashnand** [comment]
@petyosi  I think I got the root cause, the div in VirtuosoGrid component is getting rerendered and that is why classes are not getting toggled. Could you please give me some pointers on how can I control this rerendering in the VirtuosoGrid component? I saw the code but it was difficult for me to get started.

**Comment by petyosi** [comment]
React dev tools gives good information on why certain component got re-rendered. I will check on the problem myself in the upcoming days, perhaps the solution is trivial.

**Comment by lesha1201** [comment]
@aakashnand I didn't go into details but I saw that you're creating a new component for `ItemContainer` and `MainGrid` on every App re-render so it causes mount/unmount of these components instead of re-render. You can move them from App or memoize them.

https://stackblitz.com/edit/react-virtuoso-animation-zpxpty?file=Hello.js

@petyosi By the way I think it would be great if `ItemContainer`, `ListContainer` and so on can be inline render function. It can be useful in case when you need to pass props to them. Currently we need to use react context to share props with `ItemContainer`, `ListContainer`

**Comment by aakashnand** [comment]
@lesha1201 Thank you so much! I understood the problem. I completely ignored the part that I was rerendering `ItemContainer` and `MainGrid` every time. @petyosi I am closing this issue thanks for quick help.

**Comment by petyosi** [comment]
> @petyosi By the way I think it would be great if `ItemContainer`, `ListContainer` and so on can be inline render function (like props `render` and `component` in react-router for example)

I am not using react-router, unfortunately, so I am probably missing something. `ItemContainer` and `ListContainer` are functional components, which means that you can inline their definitions - [like this](https://stackblitz.com/edit/react-ef1twu?file=example.js). Or do you have something else in mind? An example can help me.

**Comment by lesha1201** [comment]
@petyosi I'm currently not from computer. I meant that whatever you pass to, for example, ScrollContainer it will call React.createElement inside VirtuosoScroller (if I don't confuse something). So if we pass inline function in Virtuoso to ItemContainer it will always create a new element. But we could add ability to pass inline function and call it directly instead of passing to createElement

```jsx
const renderScrollContainer = () => <div />

// Calling render function directly
renderScrollContainer(props)

// How it will be called currently
React.createElement(renderScrollContainer, props)
```

I can send better example later
