### ISSUE TITLE
[BUG]List child component should no longer render when data is deleted in React-Redux project

### ISSUE THREAD

**Issue by stefanJi** [petyosi/react-virtuoso#980]
**Describe the bug**
Implement a message list with react-redux, when delete message, item component  should not render anymore, otherwise will case render error becuase the selector will return undefined.

**Reproduction**

https://codesandbox.io/s/virtuoso-demo-jump-gypfeh?file=/src/App.tsx

**To Reproduce**
1. Click on 'Normal List'
2. Click message 'delete'
3. Click on 'Virtuoso List'
4. Click message 'delete'
5. See error

**Expected behavior**

**Screenshots**

https://github.com/petyosi/react-virtuoso/assets/15273198/d15301d1-9909-45df-843c-05f2de674d24

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome

**Comment by petyosi** [comment]
My guess is that the Redux state management updates its data faster than the Virtuoso component. Just use the regular way to access the virtualized list data, there's no need to pass ids and re-fetch from redux.

**Comment by Isti115** [comment]
Sorry to bump a closed issue, but I don`t think that the proposed workaround of simply passing all the required data through virtuoso is always a viable solution. It can prevent otherwise perfectly valid abstractions from being used, which may lead to less separation and thus harder maintainability in the codebase. As far as I can see with my currently limited knowledge about the library, I feel like there should be a way for virtuoso to prevent this from happening in the first place. If I'll have the time for it, I'll try to look into the code and propose a proper solution.
